In [1]:
import statsmodels.api as sm
import numpy as np
import pandas as pd
from sklearn.preprocessing import  MinMaxScaler
from sklearn.preprocessing import  OneHotEncoder 

# importar el data set
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, 4].values
dataset.head(5)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
# determine categorical and numerical features
numerical = X.select_dtypes(include=['int64', 'float64'])
categorical = X.select_dtypes(include=['object', 'bool'])

enc = OneHotEncoder(categories='auto')
onehotlabels = enc.fit_transform(categorical).toarray()
onehotlabels = onehotlabels[:,1:]  # Evitando co-liealidad

# Normalizar solo datos numericos
X = numerical.iloc[:,:].values
sc_X = MinMaxScaler()
x_norm = sc_X.fit_transform(X)

##### Concatenar onehotlabels con X 
X_completo = np.concatenate((onehotlabels,x_norm),axis=1)

In [3]:
pd.DataFrame(X_completo).head(5)

     0    1         2         3         4
0  0.0  1.0  1.000000  0.651744  1.000000
1  0.0  0.0  0.983359  0.761972  0.940893
2  1.0  0.0  0.927985  0.379579  0.864664
3  0.0  1.0  0.873136  0.512998  0.812235
4  1.0  0.0  0.859438  0.305328  0.776136

## **Tarea**

1. Aplicar statsmodels Ordinary Least Square (OLS) a dataframe
2. Analizar p-value de cada variables independientes
3. Aplicar algoritmo de eliminación hacia atrás
4. Analizar resultados desde el punto de vista de
               R-Cuadrado y R-Cuadrado ajustado

In [11]:
def backwardElimination(y,X,sl):
    numVars = X.shape[1]   
    for i in range(0, numVars):        
        regressor_OLS = sm.OLS(y, X).fit()     
        maxVar = max(regressor_OLS.pvalues)  
        print(regressor_OLS.summary())   
        if maxVar > sl:  
            for j in range(0, numVars - i):                
                if (regressor_OLS.pvalues[j] == maxVar):                    
                    X = X.drop(features[j-1],axis=1)
                    features.remove(features[j-1])